low:
    - rule:
        cwe_ids:
            - "319"
        id: javascript_lang_http_insecure
        title: Connection with an unsecure HTTP communication detected.
        description: |
            ## Description

            Applications should only connect to API using HTTPS connections. This rule checks that all HTTP connections use HTTPS.

            ❌ Avoid using unsecured outgoing HTTP communication, especially in the context of API calls:

            ```javascript
            const response = axios.get('http://insecure-api.com')
            ```

            ✅ Ensure to always connect though HTTPS:

            ```javascript
            const response = axios.get('https://secure-api.com')
            ```

            ## Resources
            - [OWASP insecure transport](https://owasp.org/www-community/vulnerabilities/Insecure_Transport)
        documentation_url: https://docs.bearer.com/reference/rules/javascript_lang_http_insecure
      line_number: 7
      full_filename: /tmp/scan/axios_with_config_insecure.js
      filename: .
      source:
        location:
            start: 7
            end: 7
            column:
                start: 1
                end: 14
      sink:
        location:
            start: 7
            end: 7
            column:
                start: 1
                end: 14
        content: axios(config)
      parent_line_number: 7
      snippet: axios(config)
      fingerprint: 152209b1605ebd60ec2a741fa69edfbe_0
      old_fingerprint: 5a93732b2b79d551538c8f8d5a8a23cc_0

