medium:
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: javascript_express_default_cookie_config
        title: Cookie with default config detected.
        description: |
            ## Description
            To make sure cookies don't open your application up to exploits or unauthorized access, don't use default cookie values.

            ## Remediations
            ✅ Instead of the default cookie name, use generic names.

            ✅ Always set a maxAge or expires value

            ## Resources
            - [Express Security Best Practices](https://expressjs.com/en/advanced/best-practice-security.html#use-cookies-securely)
        documentation_url: https://docs.bearer.com/reference/rules/javascript_express_default_cookie_config
      line_number: 11
      filename: /tmp/scan/default_express_session_cookie_config.js
      parent_line_number: 11
      snippet: '{}'
      fingerprint: 5e309d73fe6acded38143ab3e848d4ed_0
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: javascript_express_default_cookie_config
        title: Cookie with default config detected.
        description: |
            ## Description
            To make sure cookies don't open your application up to exploits or unauthorized access, don't use default cookie values.

            ## Remediations
            ✅ Instead of the default cookie name, use generic names.

            ✅ Always set a maxAge or expires value

            ## Resources
            - [Express Security Best Practices](https://expressjs.com/en/advanced/best-practice-security.html#use-cookies-securely)
        documentation_url: https://docs.bearer.com/reference/rules/javascript_express_default_cookie_config
      line_number: 17
      filename: /tmp/scan/default_express_session_cookie_config.js
      parent_line_number: 17
      snippet: |-
        {
              domain: "example.com",
              secure: true,
              httpOnly: false,
              maxAge: 24 * 60 * 60 * 1000,
              path: "/some-path",
            }
      fingerprint: 5e309d73fe6acded38143ab3e848d4ed_1
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: javascript_express_default_cookie_config
        title: Cookie with default config detected.
        description: |
            ## Description
            To make sure cookies don't open your application up to exploits or unauthorized access, don't use default cookie values.

            ## Remediations
            ✅ Instead of the default cookie name, use generic names.

            ✅ Always set a maxAge or expires value

            ## Resources
            - [Express Security Best Practices](https://expressjs.com/en/advanced/best-practice-security.html#use-cookies-securely)
        documentation_url: https://docs.bearer.com/reference/rules/javascript_express_default_cookie_config
      line_number: 29
      filename: /tmp/scan/default_express_session_cookie_config.js
      parent_line_number: 29
      snippet: |-
        {
              domain: "example.com",
              secure: true,
              httpOnly: false,
              name: "my-custom-cookie-name",
            }
      fingerprint: 5e309d73fe6acded38143ab3e848d4ed_2

