high:
    - rule:
        cwe_ids:
            - "201"
        id: ruby_third_parties_google_dataflow
        title: Sensitive data sent to Google Dataflow detected.
        description: |
            ## Description
            Leaking sensitive data to a third-party service is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Google Dataflow.

            ## Remediations

            When sending data to third-party services, ensure all sensitive data is removed.

            ## Resources
            - [Google Dataflow Docs](https://cloud.google.com/ruby/docs/reference/google-cloud-dataflow/latest)
        documentation_url: https://docs.bearer.com/reference/rules/ruby_third_parties_google_dataflow
      line_number: 8
      full_filename: /tmp/scan/datatype_in_config.rb
      filename: .
      category_groups:
        - PII
        - Personal Data
      source:
        location:
            start: 8
            end: 8
            column:
                start: 3
                end: 60
        content: 'config.metadata = { current_user_id: current_user.email }'
      sink:
        location:
            start: 8
            end: 8
            column:
                start: 40
                end: 58
      parent_line_number: 8
      snippet: 'config.metadata = { current_user_id: current_user.email }'
      fingerprint: 413255d6456534b1be7ccdeddaeeb019_0
      old_fingerprint: 683aa89d1050699bb8cd3c09c42ad033_0
    - rule:
        cwe_ids:
            - "201"
        id: ruby_third_parties_google_dataflow
        title: Sensitive data sent to Google Dataflow detected.
        description: |
            ## Description
            Leaking sensitive data to a third-party service is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Google Dataflow.

            ## Remediations

            When sending data to third-party services, ensure all sensitive data is removed.

            ## Resources
            - [Google Dataflow Docs](https://cloud.google.com/ruby/docs/reference/google-cloud-dataflow/latest)
        documentation_url: https://docs.bearer.com/reference/rules/ruby_third_parties_google_dataflow
      line_number: 14
      full_filename: /tmp/scan/datatype_in_config.rb
      filename: .
      category_groups:
        - PII
        - Personal Data
      source:
        location:
            start: 14
            end: 14
            column:
                start: 1
                end: 65
        content: 'client_config.metadata = { current_user_id: current_user.email }'
      sink:
        location:
            start: 14
            end: 14
            column:
                start: 45
                end: 63
      parent_line_number: 14
      snippet: 'client_config.metadata = { current_user_id: current_user.email }'
      fingerprint: 413255d6456534b1be7ccdeddaeeb019_1
      old_fingerprint: 683aa89d1050699bb8cd3c09c42ad033_1

