high:
    - rule:
        cwe_ids:
            - "201"
        id: ruby_third_parties_google_dataflow
        title: Sensitive data sent to Google Dataflow detected.
        description: |
            ## Description
            Leaking sensitive data to a third-party service is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Google Dataflow.

            ## Remediations

            When sending data to third-party services, ensure all sensitive data is removed.

            ## Resources
            - [Google Dataflow Docs](https://cloud.google.com/ruby/docs/reference/google-cloud-dataflow/latest)
        documentation_url: https://docs.bearer.com/reference/rules/ruby_third_parties_google_dataflow
      line_number: 8
      filename: /tmp/scan/datatype_in_config.rb
      category_groups:
        - PII
        - Personal Data
      parent_line_number: 8
      snippet: 'config.metadata = { current_user_id: current_user.email }'
      fingerprint: 683aa89d1050699bb8cd3c09c42ad033_0
    - rule:
        cwe_ids:
            - "201"
        id: ruby_third_parties_google_dataflow
        title: Sensitive data sent to Google Dataflow detected.
        description: |
            ## Description
            Leaking sensitive data to a third-party service is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Google Dataflow.

            ## Remediations

            When sending data to third-party services, ensure all sensitive data is removed.

            ## Resources
            - [Google Dataflow Docs](https://cloud.google.com/ruby/docs/reference/google-cloud-dataflow/latest)
        documentation_url: https://docs.bearer.com/reference/rules/ruby_third_parties_google_dataflow
      line_number: 14
      filename: /tmp/scan/datatype_in_config.rb
      category_groups:
        - PII
        - Personal Data
      parent_line_number: 14
      snippet: 'client_config.metadata = { current_user_id: current_user.email }'
      fingerprint: 683aa89d1050699bb8cd3c09c42ad033_1

