patterns:
  - pattern: |
      Cipher.getInstance($<ARGUMENT>);
    filters:
      - variable: ARGUMENT
        regex: DESede.*
  - pattern: |
      KeyGenerator.getInstance("DES")
languages:
  - java
trigger:
  match_on: presence
metadata:
  description: "Use of deprecated encryption algorithm detected"
  remediation_message: |
    ## Description

    Triple DES (3DES or DESede) is considered deprecated and unsecure. Upgrade to latest cipher for eg. AES.

    ## Remediations

    ✅ Use strong cipher such as AES

    ```java
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.ENCRYPT_MODE, key);
        byte[] cipherText = cipher.doFinal(plainText);
    ```

    ## Resources
    - [OWASP SQL injection explained](https://owasp.org/www-community/attacks/SQL_Injection)
    - [OWASP SQL injection prevention cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html)
  cwe_id:
    - 89
  id: "java_lang_desede_usage"
  documentation_url: https://docs.bearer.com/reference/rules/java_lang_desede_usage
