patterns:
  - pattern: |
      new $<METHOD>($<...>$<FILE_USER_INPUT>$<...>);
    filters:
      - variable: METHOD
        regex: (java.)?(io.)?(File|FileReader|FileWriter|FileInputStream|FileOutputStream)
      - variable: FILE_USER_INPUT
        detection: java_lang_path_traversal_user_input
        scope: result
  - pattern: |
      new $<METHOD>($<...>$<FILE_USER_INPUT>$<...>);
    filters:
      - variable: METHOD
        regex: ^(java.)?(io.)?(File.)?(createTempFile|createTempDirectory)
      - variable: FILE_USER_INPUT
        detection: java_lang_path_traversal_user_input
        scope: result
  - pattern: |
      new $<METHOD>($<...>$<FILE_USER_INPUT>$<...>);
    filters:
      - variable: METHOD
        regex: ^(javax.)?(activation.)?FileDataSource
      - variable: FILE_USER_INPUT
        detection: java_lang_path_traversal_user_input
        scope: result
  - pattern: |
      new $<METHOD>($<...>$<FILE_USER_INPUT>$<...>);
    filters:
      - variable: METHOD
        regex: ^(java.)?(nio.)?(file.)?(Files.)?(createTempFile|createTempDirectory)
      - variable: FILE_USER_INPUT
        detection: java_lang_path_traversal_user_input
        scope: result
  - pattern: |
      new $<METHOD>($<...>$<FILE_USER_INPUT>$<...>);
    filters:
      - variable: METHOD
        regex: ^(java.)?(nio.)?(file.)?(Paths.)?get
      - variable: FILE_USER_INPUT
        detection: java_lang_path_traversal_user_input
        scope: result
auxiliary:
  - id: java_lang_path_traversal_user_input
    sanitizer: java_lang_path_traversal_sanitized_input
    patterns:
      - pattern: |
          $<PARAMETER_REQUEST>.$<PARAMETER_METHOD>()
        filters:
          - variable: PARAMETER_REQUEST
            values:
              - req
              - request
          - variable: PARAMETER_METHOD
            values:
              - getParameterValues
              - getParameter
      - pattern: $<COOKIE_REQUEST>.getCookies()
        filters:
          - variable: COOKIE_REQUEST
            values:
              - req
              - request
  - id: java_lang_path_traversal_sanitized_input
    patterns:
      - pattern: FilenameUtils.getName($<!>$<_>)
languages:
  - java
trigger:
  match_on: presence
metadata:
  description: Possible path traversal vulnerability detected
  remediation_message: |
    ## Description

    Allowing unsanitized user input in path resolution methods means an attacker could gain access to files and folders outside of the intended scope.

    ## Remediations
    ❌ Avoid wherever possible

    ✅ Sanitize user input when resolving paths, for example:
    Use `FilenameUtils.getName()` to mitigate against unwanted patterns in the path (such as `\..\..`)

    ```java
      public class Cls extends HttpServlet
      {

          public void handleRequest(HttpServletRequest request, HttpServletResponse response)
          {
              String image = request.getParameter("user_profile_picture");
              File file = new File("user/profile/" + FilenameUtils.getName(image));
          }
      }
    ```

    ## Resources
    - [OWASP path traversal](https://owasp.org/www-community/attacks/Path_Traversal)
  cwe_id:
    - 22
  id: java_lang_path_traversal
  documentation_url: https://docs.bearer.com/reference/rules/java_lang_path_traversal
