patterns:
  - pattern: |
      MessageDigest.getInstance($<ALGORITHM>)
    filters:
      - variable: ALGORITHM
        regex: (?i)['"](MD5|SHA-1)['"]
languages:
  - java
trigger:
  match_on: presence
metadata:
  description: "Weak encryption library usage detected"
  remediation_message: |
    ## Description

    Sensitive data should be encrypted with strong encryption algorithms like aes-256-cbc

    ## Remediations

    According to [OWASP](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/04-Testing_for_Weak_Encryption): MD5, RC4, DES, Blowfish, SHA1. 1024-bit RSA or DSA, 160-bit ECDSA (elliptic curves), 80/112-bit 2TDEA (two key triple DES) are considered as weak hash/encryption algorithms and therefore shouldn't be used.

    ✅ Use stronger encryption algorithms when storing data.

    ```java
      MessageDigest md = MessageDigest.getInstance("SHA-256");
    ```

    ## Resources
    - [Java MessageDigest class](https://docs.oracle.com/javase/8/docs/api/java/security/MessageDigest.html)
  cwe_id:
    - 327
  id: "java_lang_weak_encryption"
  documentation_url: https://docs.bearer.com/reference/rules/java_lang_weak_encryption
