languages:
  - ruby
patterns:
  - pattern: |
      class $<_>
        $<!>validates :password, length: { minimum: $<LENGTH> }
      end
    filters:
      - variable: LENGTH
        less_than: 8
  - pattern: |
      class $<_>
        $<!>devise password_length: $<MIN_LENGTH>..$<MAX_LENGTH>
      end
    filters:
      - either:
          - variable: MAX_LENGTH
            less_than: 35
          - variable: MIN_LENGTH
            less_than: 8
  - pattern: |
      Devise.setup do |$<CONFIG:identifier>|
        $<!>$<CONFIG>.password_length = $<MIN_LENGTH>..$<MAX_LENGTH>
      end
    filters:
      - variable: MIN_LENGTH
        less_than: 8
  - pattern: |
      Devise.setup do |$<CONFIG:identifier>|
        $<!>$<CONFIG>.password_length = $<LENGTH>
      end
    filters:
      - variable: LENGTH
        less_than: 8
trigger:
  match_on: presence
  data_types_required: true
severity: medium
metadata:
  description: "Usage of weak password constraint"
  remediation_message: |-
    ## Description

    Weak password constraints can compromise system security. Ensure that your application's password policy enforces a minimum length of 8 characters during password creation or update processes.

    ## Remediations

    - **Do** enforce a minimum password length of at least 8 characters. This helps in creating stronger passwords that are more resistant to brute-force attacks.
      ```ruby
      validates :password, presence: true, length: { minimum: 8, maximum: 255 }
      ```
    - **Do** implement this validation at the model level in your application to ensure that all passwords meet the minimum length requirement.

    ## References

    - [OWASP Authentication Cheat Sheet on proper password strength controls](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls)
    - [Devise gem for Ruby on Rails](https://github.com/heartcombo/devise)
  cwe_id:
    - 521
  id: ruby_rails_password_length
  documentation_url: https://docs.bearer.com/reference/rules/ruby_rails_password_length
  cloud_code_suggestions: true
