medium:
    - rule:
        cwe_ids:
            - "523"
            - "522"
        id: javascript_express_default_session_config
        title: Session cookie with default config detected.
        description: |
            ## Description
            To make sure session cookies don't open your application up to exploits or unauthorized access, don't use default cookie values.

            ## Remediations
            ✅ Instead of the default session name, use generic names.

            ## Resources
            - [Express Security Best Practices](https://expressjs.com/en/advanced/best-practice-security.html#use-cookies-securely)
        documentation_url: https://docs.bearer.com/reference/rules/javascript_express_default_session_config
      line_number: 9
      full_filename: /tmp/scan/default_session_config.js
      filename: .
      source:
        location:
            start: 9
            end: 9
            column:
                start: 17
                end: 19
        content: '{}'
      sink:
        location:
            start: 9
            end: 9
            column:
                start: 17
                end: 19
      parent_line_number: 9
      snippet: '{}'
      fingerprint: 037459ef0f358c29fa721b91de9aa785_0
      old_fingerprint: 6737918c527517aac5dd3fec39d0524e_0

