high:
    - rule:
        cwe_ids:
            - "201"
        id: javascript_third_parties_sentry
        title: Sensitive data sent to Sentry detected.
        description: |
            ## Description
            Leaking sensitive data to third-party loggers is a common cause of data leaks and can lead to data breaches. This rule looks for instances of sensitive data sent to Sentry.

            ## Remediations

            When logging errors or events, ensure all sensitive data is removed.

            ## Resources
            - [Sentry Docs](https://docs.sentry.io/)
        documentation_url: https://docs.bearer.com/reference/rules/javascript_third_parties_sentry
      line_number: 2
      full_filename: /tmp/scan/javascript_configure_scope_set_tag.js
      filename: .
      data_type:
        category_uuid: cef587dd-76db-430b-9e18-7b031e1a193b
        name: Email Address
      category_groups:
        - PII
        - Personal Data
      source:
        location:
            start: 2
            end: 2
            column:
                start: 30
                end: 40
      sink:
        location:
            start: 2
            end: 2
            column:
                start: 3
                end: 41
        content: scope.setTag("user_email", user.email)
      parent_line_number: 2
      snippet: scope.setTag("user_email", user.email)
      fingerprint: af49328f7c7aa692f05a50dc6ccda334_0
      old_fingerprint: baa2aad5d37ea6031b2255fd63fdba6c_0

