patterns:
  - pattern: |
      {
        cookie: $<!>$<HASH_CONTENT>
      }
    filters:
      - variable: HASH_CONTENT
        detection: javascript_express_default_cookie_config_hash_val
        scope: cursor
      - either:
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_name_attribute
              scope: cursor
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_expiry_attribute
              scope: cursor
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_path_attribute
              scope: cursor
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_domain_attribute
              scope: cursor
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_secure_attribute
              scope: cursor
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_httponly_attribute
              scope: cursor
  - pattern: |
      cookieSession($<!>$<HASH_CONTENT>)
    filters:
      - variable: HASH_CONTENT
        detection: javascript_express_default_cookie_config_hash_val
      - either:
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_name_attribute
              scope: cursor
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_expiry_attribute
              scope: cursor
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_path_attribute
              scope: cursor
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_domain_attribute
              scope: cursor
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_secure_attribute
              scope: cursor
          - not:
              variable: HASH_CONTENT
              detection: javascript_express_default_cookie_config_httponly_attribute
              scope: cursor
languages:
  - javascript
auxiliary:
  - id: javascript_express_default_cookie_config_hash_val
    patterns:
      - |
        {}
  - id: javascript_express_default_cookie_config_name_attribute
    patterns:
      - |
        { name: $<_> }
  - id: javascript_express_default_cookie_config_expiry_attribute
    patterns:
      - |
        { maxAge: $<_> }
      - |
        { expires: $<_> }
  - id: javascript_express_default_cookie_config_path_attribute
    patterns:
      - |
        { path: $<_> }
  - id: javascript_express_default_cookie_config_domain_attribute
    patterns:
      - |
        { domain: $<_> }
  - id: javascript_express_default_cookie_config_secure_attribute
    patterns:
      - |
        { secure: $<_> }
  - id: javascript_express_default_cookie_config_httponly_attribute
    patterns:
      - |
        { httpOnly: $<_> }
severity: medium
metadata:
  description: "Cookie with default config detected."
  remediation_message: |
    ## Description
    To make sure cookies don't open your application up to exploits or unauthorized access, don't use default cookie values.

    ## Remediations
    ✅ Instead of the default cookie name, use generic names.

    ✅ Always set a maxAge or expires value

    ## Resources
    - [Express Security Best Practices](https://expressjs.com/en/advanced/best-practice-security.html#use-cookies-securely)
  cwe_id:
    - 523
    - 522
  id: javascript_express_default_cookie_config
  documentation_url: https://docs.bearer.com/reference/rules/javascript_express_default_cookie_config
