patterns:
  - pattern: |
      https.createServer()
auxiliary:
  - id: javascript_express_https_protocol_missing_http_server
    patterns:
      - $<_>.createServer()
languages:
  - javascript
trigger:
  match_on: absence
  required_detection: javascript_express_https_protocol_missing_http_server
metadata:
  description: "Missing secure HTTP server configuration"
  remediation_message: |-
    ## Description

    Failing to configure your HTTP server to use HTTPS can expose data to interception and manipulation. HTTPS, which incorporates TLS (Transport Layer Security), encrypts data in transit and therefore provides a more secure communication channel than HTTP.

    ## Remediations

    - **Do** use the `https` module for creating secure servers in your applications. This ensures that data transmitted between the server and clients is encrypted.
    ```javascript
    var https = require('https');
    var express = require('express');
    var app = express();

    var httpsServer = https.createServer(app);
    httpsServer.listen(8080);
    ```

    ## References

    - [Express Security Best Practices: use TLS](https://expressjs.com/en/advanced/best-practice-security.html#use-tls)
  cwe_id:
    - 319
  id: javascript_express_https_protocol_missing
  documentation_url: https://docs.bearer.com/reference/rules/javascript_express_https_protocol_missing
  cloud_code_suggestions: true
severity: critical
