imports:
  - java_shared_lang_instance
  - java_shared_lang_user_input
patterns:
  - pattern: |
      $<SQL_CONN>.setCatalog($<USER_INPUT>);
    filters:
      - variable: SQL_CONN
        detection: java_shared_lang_instance
        scope: cursor
        filters:
          - variable: JAVA_SHARED_LANG_INSTANCE_TYPE
            regex: \A(java\.sql\.)?Connection\z
      - variable: USER_INPUT
        detection: java_shared_lang_user_input
        scope: cursor
languages:
  - java
severity: medium
metadata:
  description: Unsanitized user input in SQL catalog configuration
  remediation_message: |-
    ## Description

    Using unsanitized user input to configure a SQL Connection's catalog can lead to security vulnerabilities. This practice allows attackers to manipulate the catalog name in the `setCatalog` method, potentially causing harmful or unintended actions in the application.

    ## Remediations

    - **Do not** use direct user input for setting the SQL database's catalog. Always sanitize or validate input before using it in your database configuration.

    ## References

    - [Java SQL Connection](https://docs.oracle.com/en/java/javase/21/docs/api/java.sql/java/sql/Connection.html)
  cwe_id:
    - 15
  id: java_lang_external_config_control
  documentation_url: https://docs.bearer.com/reference/rules/java_lang_external_config_control
