imports:
  - java_shared_lang_instance
patterns:
  - pattern: $<EMAIL_CLIENT>.setSSLCheckServerIdentity($<TRUE>);
    filters:
      - variable: EMAIL_CLIENT
        detection: java_shared_lang_instance
        scope: cursor
        filters:
          - variable: JAVA_SHARED_LANG_INSTANCE_TYPE
            regex: \A(org\.apache\.commons\.mail\.)?(SimpleEmail|Email|MultiPartEmail|HtmlEmail|ImageHtmlEmail)\z
      - variable: "TRUE"
        detection: java_lang_missing_smtp_ssl_host_check_true
        scope: cursor
trigger:
  match_on: absence
  required_detection: java_lang_missing_smtp_ssl_host_check_set_ssl
auxiliary:
  - id: java_lang_missing_smtp_ssl_host_check_set_ssl
    patterns:
      - pattern: $<EMAIL_CLIENT2>.setSSLOnConnect($<TRUE>);
        filters:
          - variable: EMAIL_CLIENT2
            detection: java_shared_lang_instance
            scope: cursor
            filters:
              - variable: JAVA_SHARED_LANG_INSTANCE_TYPE
                regex: \A(org\.apache\.commons\.mail\.)?(SimpleEmail|Email|MultiPartEmail|HtmlEmail|ImageHtmlEmail)\z
          - variable: "TRUE"
            detection: java_lang_missing_smtp_ssl_host_check_true
            scope: cursor
  - id: java_lang_missing_smtp_ssl_host_check_true
    patterns:
      - "true;"
languages:
  - java
metadata:
  description: "Missing SSL host check in SMTP"
  remediation_message: |-
    ## Description

    Missing SSL host check in SMTP can compromise the security of email communications. This vulnerability arises when SSL certificates are not properly validated to ensure they originate from the anticipated host, potentially allowing attackers to pose as legitimate entities by leveraging valid SSL certificates from other hosts.

    ## Remediations

    - **Do** configure your email client to verify the server's identity. This step is crucial to prevent attackers from impersonating a trusted server, which could lead to redirection or spoofing attacks.
      ```java
      Email email = new Email();
      email.setSSLOnConnect(true);
      email.setSSLCheckServerIdentity(true);
      ```
  cwe_id:
    - 297
  id: java_lang_missing_smtp_ssl_host_check
  documentation_url: https://docs.bearer.com/reference/rules/java_lang_missing_smtp_ssl_host_check
  cloud_code_suggestions: true
severity: medium
