name: Canary Integration Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version: ["canary-amd64"]
        group:
          [
            "javascript/express",
            "javascript/lang",
            "javascript/react",
            "javascript/third_parties",
            "ruby/lang",
            "ruby/rails",
            "ruby/third_parties",
            "java/lang",
            "java/spring",
            "php/lang",
            "php/symfony",
            "php/third_parties",
            "python/lang",
            "go/lang",
            "go/gosec",
            "go/gorilla",
          ]
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - name: Test ${{ matrix.group }}
        run: BEARER_VERSION=${{matrix.version}} yarn test tests/${{ matrix.group }}
        shell: bash
