name: Integration Tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
permissions:
  contents: read
jobs:
  set_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load.outputs.matrix }}
    steps:
      - id: load
        run: $(cat ./scripts/test_matrix.json | jq -c) >> $GITHUB_OUTPUT
  build:
    needs: set_matrix
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        group: ${{ fromJSON(needs.set_matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Test ${{ matrix.group }}
        run: ./scripts/run_tests.sh  ${{ matrix.group }}
        shell: bash
