name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version: ["latest"]
        group:
          [
            "javascript/express",
            "javascript/lang",
            "javascript/react",
            "javascript/third_parties",
            "ruby/lang",
            "ruby/rails",
            "ruby/third_parties",
            "java/lang",
            "java/spring",
            "php/lang",
            "php/symfony",
            "php/third_parties",
            "python/lang",
            "go/lang",
          ]
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: Test ${{ matrix.group }}
        run: BEARER_VERSION=${{matrix.version}} npm test tests/${{ matrix.group }}
        shell: bash
