name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        group:
          [
            "javascript/express",
            "javascript/hapi",
            "javascript/lang",
            "javascript/node",
            "javascript/react",
            "javascript/third_parties",
            "ruby/lang",
            "ruby/rails",
            "ruby/third_parties",
            "java/lang",
            "java/spring",
            "java/android",
            "java/third_parties",
            "php/lang",
            "php/symfony",
            "php/third_parties",
            "python/django",
            "python/lang",
            "go/lang",
            "go/gosec",
            "go/gorilla",
            "go/third_parties",
          ]
    steps:
      - uses: actions/checkout@v4
      - run: yarn install --frozen-lockfile
      - run: curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
      - run: ./bin/bearer version
      - name: Test ${{ matrix.group }}
        run: BEARER_BIN=./bin/bearer yarn test tests/${{ matrix.group }}
        shell: bash
